kind: Environment
name: NestJS / React / MongoDB boilerplate
type: primary
components:
    -
        kind: Application
        name: api
        gitRepo: 'https://github.com/bunnyshell/templates.git'
        gitBranch: nestjs-rest-api/v0.3.0
        gitApplicationPath: components/nestjs-rest-api
        dockerCompose:
            build:
                context: ./components/nestjs-rest-api
                dockerfile: .docker/Dockerfile
                target: dev
            ports:
                - '9000:9000'
        hosts:
            -
                hostname: 'api-{{ env.base_domain }}'
                path: /
                servicePort: 9000
    -
        kind: Database
        name: mongo
        dockerCompose:
            environment:
                MONGO_INITDB_DATABASE: books
            image: 'mongo:4.4'
            ports:
                - '27017:27017'
        volumes:
            -
                name: data-volume
                mount: /data/db
                subPath: ''
    -
        kind: Application
        name: app
        gitRepo: 'https://github.com/bunnyshell/templates.git'
        gitBranch: react-books-app/v0.5.0
        gitApplicationPath: components/react-books-app
        dockerCompose:
            build:
                context: ./components/react-books-app
                dockerfile: .docker/Dockerfile
                target: dev
            environment:
                REACT_APP_BASE_API: 'https://{{ components.api.ingress.hosts[0] }}'
            ports:
                - '8080:8080'
        hosts:
            -
                hostname: 'app-{{ env.base_domain }}'
                path: /
                servicePort: 8080
volumes:
    -
        name: data-volume
        size: 1Gi
        type: disk
