version: '3.4'
services:
  api:
    container_name: api
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: ${BACKEND_BUILD_TARGET:-dev} # use "prod" for production
    environment:
      - DB_HOST=db # name of the "db" service
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-toor}
    ports:
      - "9000:9000"
    depends_on:
      - mongo
  mongo:
    image: mongodb/mongodb-community-server:${MONGO_VERSION:latest}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-toor}
    # ports:
    #   - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
