version: '3.4'
services:
  api:
    container_name: api
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
      target: ${BACKEND_BUILD_TARGET:-dev} # use "prod" for production
    volumes:
       - ./../:/usr/src/app/backend
    environment:
      - POSTGRES_HOST=db # name of the "db" service
      - POSTGRES_DB=bunny_books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=need-to-replace
      - FRONTEND_URL=${FRONTEND_URL-http://localhost:8080}
    ports:
      - "9000:9000"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: main
    volumes:
      - db:/data/db

volumes:
  db:
